FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /opt/vllm_standalone_bench

COPY requirements.txt ./requirements.txt
COPY run_bench_multi.py run_bench_serve.py ./
COPY vllm_bench ./vllm_bench

RUN pip install --no-cache-dir -r requirements.txt openpyxl modelscope

CMD ["python", "/opt/vllm_standalone_bench/run_bench_multi.py", "--help"]
